/* Generated by Together */

#include "TDistNorm.h"
/* Generated by Together */
OOPMReturnType TDistNorm::Execute ()
{
#warning "Execute not completely implemented"
	double val = ComputeLocalNorm();
  //On the serial implementation the value of normb is set to 1 if the computed norm is 0
  //How to implement
	TTaskComm * tcmm = new TTaskComm(0);
	tcmm->SetValue(val);
	OOPDataVersion ver(fId_Target.Version);
	ver.SetVersion(1,-1);
	tcmm->AddDependentData(OOPMDataDepend(fId_Target, EWrite, ver));
	tcmm->Submit();
	return ESuccess;	// execute the task, verifying that
}
long TDistNorm::ExecTime ()
{
	return -1;
}
double TDistNorm::ComputeLocalNorm(){
#warning "ComputeLocalNorm not implemented"
	return 0.;
}
