/* Generated by Together */
#ifndef TPARVECTOR_H
#define TPARVECTOR_H
//#include "oopsaveable.h"
#include <vector>
class   TParVector:public TPZSaveable
{
      public:
	TParVector ();
	long    GetClassID ();
	int     Write(OOPStorageBuffer * buf, int classid);
	int     Read(OOPStorageBuffer * buf, void *context);
	void    Resize (int size);
	void    SetVector (vector < double *>data);
      double & operator[]( const int index ) const;
      static TPZSaveable *Restore(OOPReceiveStorage *buf);
      int NElements(){
            return fData.size();
      }

      private:
	vector < double *>fData;
};
#endif // TPARRHS_H
