/* Generated by Together */

#ifndef TUPDATERESIDUE_H
#define TUPDATERESIDUE_H
#include "ooptask.h"
#include "bicgdefs.h"

class TUpdateResidue : public OOPTask {
public:
  TUpdateResidue(int nproc);
  /**
   * Returns the estimated execution time.
   * returns 0 if the task is instantaneous
   * returns > 0 if estimate is known
   * return < 0 if no estimate is known
   */
  virtual long ExecTime ();

	/**
	 * Execute the task, verifying that all needed data acesses are satisfied.
	 */
	virtual OOPMReturnType Execute ();

	/**
	 * Returns last created Id.
	 */
	virtual long GetClassID ()
	{
		return TUPDATERESIDUE_ID;
	}
};

#endif //TUPDATERESIDUE_H
