/* Generated by Together */

#ifndef LOCALCOMPRESIDUAL_H
#define LOCALCOMPRESIDUAL_H
#include "ooptask.h"
//class OOPMReturnType;
class LocalCompResidual : public OOPTask {
public:    

    /**
        	* Execute the task, verifying that all needed data acesses are satisfied.
        	*/
	virtual OOPMReturnType Execute ();    

    LocalCompResidual(int ProcId);
};
#endif //LOCALCOMPRESIDUAL_H
