/* Generated by Together */


#include "TContribution.h"



vector<int> & TContribution::DestinationVector(int index){
    return fLocalIndices[index];
}


void TContribution::InitializeRandom(int i){
    seed();
    int rs = rnd(10)%1;
}
