/* Generated by Together */
#include "TParMesh.h"
class TPZStream;
TParMesh::TParMesh ()
{
}
TParMesh::~TParMesh() {
}
  /**
   * Packs the object in on the buffer so it can be transmitted through the network.
   * The Pack function  packs the object's class_id while function Unpack() doesn't,
   * allowing the user to identify the next object to be unpacked.
   * @param *buff A pointer to TSendStorage class to be packed.
   */
int TParMesh::Write (TPZStream * buf) {
	TPZSaveable::Write(*buf);
	return 1;
}
  /**
   * Unpacks the object class_id
   * @param *buff A pointer to TSendStorage class to be unpacked.
   */
int TParMesh::Read (TPZStream * buf) {
	TPZSaveable::Read(*buf);
	return 1;
}
TPZSaveable *TParMesh::Restore (TPZStream * buf) {
	TParMesh *pm = new TParMesh();
	pm->Read(buf);
	return pm;
}
