/* Generated by Together */

#ifndef TPARRHS_H
#define TPARRHS_H
#include "oopsaveable.h"
class TParRhs : public OOPSaveable {
public:    

    TParRhs();
	long GetClassID();
	long fClassId;
};
#endif //TPARRHS_H
