// -*- c++ -*-

/* Generated by Together */

#ifndef TPARTITIONRELATION_H
#define TPARTITIONRELATION_H

#include "TContribution.h"
#include "oopsaveable.h"
#include <vector>

/**
 * This class describe the relationship between the partitions of a mesh
 */
class TPartitionRelation : public OOPSaveable {
public:

	long GetClassID();
	TPartitionRelation();
  TPartitionRelation(int numpart);
    /**
     * Returns the total number of 
     */

  	static TPartitionRelation *CreateRandom(int numpart);

    int GetNPartitions();

    TContribution &GetRelation(int parfrom, int parto);

    int IncomingContribution(int partition);

    /**
     * Returns a vector containing the ID of all the partitions to each the local partitions will contribute to. 
     */
    int OutgoingContribution(int partition);

    void Print(ostream &out);

    /**
     * inform to the relation table the mesh id
     */
    void SetMeshId(int index, OOPObjectId &meshid);
private:    
    int fNumPartitions;
    vector< vector<TContribution > > fRelation;
	long fClassId;
};
#endif //TPARTITIONRELATION_H
