/* Generated by Together */
#ifndef TPARMESH_H
#define TPARMESH_H

#include "fluxdefs.h"
#include "pzsave.h"

class TPZStream;

class   TParMesh:public TPZSaveable
{
public:
	TParMesh ();
	virtual ~TParMesh();
	/**
	 * @brief Returns the class id for the current class.
	 */
	virtual int  ClassId () const {
		return TPARMESH_ID;
	}
	/**
	 * @brief Packs the object in on the buffer so it can be transmitted through the network. \n
	 * The Pack function  packs the object's class_id while function Unpack() doesn't,
	 * allowing the user to identify the next object to be unpacked.
	 * @param buf A pointer to TSendStorage class to be packed.
	 */
	virtual void Write (TPZStream & buf, int withclassid=0);
	/**
	 * @brief Unpacks the object class_id
	 * @param buf A pointer to TSendStorage class to be unpacked.
	 */
	virtual void Read (TPZStream & buf, void * context = 0);
	static TPZSaveable *Restore (TPZStream & buf, void * context = 0);
};

#endif // TPARMESH_H
