/* Generated by Together */

#ifndef TPARMESH_H
#define TPARMESH_H
#include "oopsaveable.h"

#include "fluxdefs.h"

class   TParMesh:public OOPSaveable
{
      public:

	TParMesh ();

	virtual ~TParMesh();
	/**
	 * Returns the class id for the current class.
	 */
	virtual long GetClassID () {
		return TPARMESH_ID;
	}

  /**
   * Packs the object in on the buffer so it can be transmitted through the network.
   * The Pack function  packs the object's class_id while function Unpack() doesn't,
   * allowing the user to identify the next object to be unpacked.
   * @param *buff A pointer to TSendStorage class to be packed.
   */
	virtual int Pack (OOPSendStorage * buf);
  /**
   * Unpacks the object class_id
   * @param *buff A pointer to TSendStorage class to be unpacked.
   */
	virtual int Unpack (OOPReceiveStorage * buf);

	static OOPSaveable *Restore (OOPReceiveStorage * buf);


};
#endif // TPARMESH_H
