/* Generated by Together */

#ifndef TPARMESH_H
#define TPARMESH_H
#include "oopsaveable.h"
class   TParMesh:public OOPSaveable
{
      public:

	TParMesh ();
	/**
	 * Returns the class id for the current class.
	 */
	virtual long GetClassID ();
      private:
	/**
	 * Holds the unique class Id for the parallel environment.
	 * @author Gustavo Camargo Longhin
	 * @since 04/06/2003
	 */
	long    fClassId;


};
#endif // TPARMESH_H
