/* Generated by Together */

#ifndef TPARSTATE_H
#define TPARSTATE_H
#include "oopsaveable.h"
class TParState : public OOPSaveable {
public:    

    TParState(int ProcId, int Trace);
};
#endif //TPARSTATE_H