/* Generated by Together */

#ifndef TPARRHS_H
#define TPARRHS_H
#include "oopsaveable.h"
class TParVector : public OOPSaveable {
public:    

    TParVector();
	long GetClassID();
	long fClassId;
};
#endif //TPARRHS_H
