/* Generated by Together */

#ifndef TPARANALYSIS_H
#define TPARANALYSIS_H

/**
 * Implements the functionalities of the Analysis classes incorporating parallelization optimization. 
 */
class TParAnalysis {
public:

    void ComputeFlux();
};
#endif //TPARANALYSIS_H