/* Generated by Together */

#include "TPartitionRelation.h"
int TPartitionRelation::OutgoingContribution(int partition){}
int TPartitionRelation::IncomingContribution(int partition){}
int TPartitionRelation::GetNPartitions(){}
