/* Generated by Together */

#include "ParCompResidual.h"
void ParCompResidual::CreateFluxesTasks(int NPartitions, Solutinos * soltions, Residuals * residuals){
    int i;
    //Data submission on DataManager
    //Ids are stored for the task/data dependence information
    for(i=0;i<fNPartitions;i++){
       id_aux_Sol = DM->SubmitObject(Solutions[i], 1);
       id_aux_Res = DM->SubmitObject(Residual[i], 1);
       fSolIds.push_back(id_aux_Sol);
       fRhsIds.push_back(id_aux_Res);
    }

    //Pointers to LocalTasks created
    LocalCompResidual * Tasks = new LocalCompResidual(fProc) (NPartitions);

    //For each LocalTask its necessary data dependence attribution
    OOPMDataState st_read = EReadAccess;
    OOPMDataState st_w = EWriteAccess;
    OOPDataVersion ver;
    //Atençao com versão!
    ver.SetLevelVersion(0,-1);
    int aux_depth;

    for(i=0;i<NPartitions;i++){
        aux_depth = Relation.GetNContributions(i);
        //Perform necessary actions to set the version for the residuals.
        Tasks[i]->AddDependentData(Relation, st_read, ver);
        Tasks[i]->AddDependentData(fSolIds[i], st_read, ver);
        Tasks[i]->AddDependentData(fRhsIds[i], st_w, ver);
    }






}
void ParCompResidual::InitializeSolutionVersion(){
    /**
    For each Flux object, obtain the number of contribution from
    and set the version object related to each flux accordingly
    */
    int ncont;
    for(i=0;i<fNPartitions;i++){
        ncont = Relation.GetNContributions(i);
        //Isso deve ser substituído por um acesso a partir da tarefa, que terá
        //acesso à versão.
        DM->IncrementLevel(fRhsIds[i], Id(), ncont, fProc);
        //DM->IncrementLevel(fRhsIds[i], ncont, fProc);
    }

}
OOPMReturnType ParCompResidual::Execute(){
    /**
      Execute the necessary task creation
     */

    /**
      Initialize the version structure on state variables (Solutions)
     */
    InitializeSolutionVersion();

    /**
      Create tasks which will calculate fluxes on the partitions.
     */
    CreateFluxesTasks();
    return ESuccess; // execute the task, verifying that
}
ParCompResidual::ParCompResidual(int ProcId): OOPTast(ProcId) {}
