/* Generated by Together */

#ifndef TMULTADD_H
#define TMULTADD_H
#include <ooptask.h>
#include <bicgdefs.h>
class TMultAdd : public OOPTask {
public:	
  TMultAdd(int proc);
    /**
    	* Returns the estimated execution time.
    	* returns 0 if the task is instantaneous
    	* returns > 0 if estimate is known
    	* return < 0 if no estimate is known
    	*/
	long ExecTime ();

	/**
	* Execute the task, verifying that all needed data acesses are satisfied.
	*/
	OOPMReturnType Execute ();

	/**
	* Returns last created Id.
	*/
	long GetClassID ()
	{
		return TMULTADD_ID;
	}
};
#endif //TMULTADD_H
