/* Generated by Together */

#ifndef OOPMATINDEX_H
#define OOPMATINDEX_H
#include "ooppardefs.h"
#include "pzsave.h"

#define OOPMATINDEXATION_ID 1006

class OOPParMatIndexation : public TPZSaveable {
	/**
	 * Holds the indexation information for contribution from the local indices (SubMatrix)
	 * to the global indices (Full Matrix).
	 */
	std::vector< std::pair< std::vector<int>, std::vector<int> > > m_Indices;
public:
	/**
	 * Sets the indexation vector
	 */
	void SetIndexationVector(std::vector< std::pair < std::vector<int> , std::vector< int > > > & theIndices);
	/**
	 * Returns the Column indexation vector.
	 # @param i : Id of the SubMatrix to which the indexation vector is being required.
	 */
	std::vector< int > GetColVector(int i);
	
	/**
	 * Returns the Row indexation vector.
	 * @param i : Id of the SubMatrix to which the indexation vector is being required.
	 */
	std::vector< int > GetRowVector(int i);
	
	
	OOPParMatIndexation();
	
	void Write(TPZStream & buf, int withclassid);
	
	void Read(TPZStream & buf, void * context);
	
	virtual int ClassId() const ;
	
	
};
#endif //OOPMATINDEX_H
