/* Generated by Together */

#ifndef TIFCONDITIONAL_H
#define TIFCONDITIONAL_H
#include <ooptask.h>
class OOPMReturnType;

/**
 * Implements an If condition. In case the it returns true the inside the if functionality is submitted as tasks, otherwise only the version of the appropriate object is incremented. 
 */
class TIfConditional : public OOPTask {
public:    

    /**
        * Returns the estimated execution time.
        * returns 0 if the task is instantaneous
        * returns > 0 if estimate is known
        * return < 0 if no estimate is known
        */
	virtual long ExecTime ();

	/**
	* Execute the task, verifying that all needed data acesses are satisfied.
	*/
	virtual OOPMReturnType Execute ();

	/**
	* Returns last created Id.
	*/
	virtual long GetClassID ()
	{
		return TDISTNORM_ID;
	}
};
#endif //TIFCONDITIONAL_H