/* Generated by Together */

#include "tmultidata.h"

TMultiData::TMultiData(){}
vector<double> TMultiData::GetVector(){
    return fData;
}
void TMultiData::SetData(vector<double> & vec){
    fData = vec;
}
long
TMultiData::GetClassID()
{
  return 1;
}
