/* Generated by Together */

#include "TIfConditional.h"
/* Generated by Together */
OOPMReturnType TIfConditional::Execute ()
{
#warning "Execute not implemented"
	return ESuccess;	// execute the task, verifying that
}
long TIfConditional::ExecTime ()
{
	return -1;
}
