/* Generated by Together */

#include "OOPInt.h"
OOPInt::OOPInt() : TPZSaveable() , fValue(0) {}
void OOPInt::Read(TPZStream & buf, void * context){
    TPZSaveable::Read(buf, context);
    buf.Read(&fValue);
    int clsid = 0;
    buf.Read(&clsid);
    if(clsid!=ClassId()){
        cerr << "ClassId missmatch on OOPInt::Read";
    }

}
void OOPInt::Write(TPZStream & buf, int withclassid){
    TPZSaveable::Write(buf, withclassid);
    buf.Write(&fValue);
    int clsid = ClassId();
    buf.Write(&clsid);
}
int OOPInt::ClassId() const {
    return OOPINT_ID;
}
