/* Generated by Together */

#include "TDotProduct.h"
/* Generated by Together */
OOPMReturnType TDotProduct::Execute ()
{
#warning "Execute not implemented"
	return ESuccess;	// execute the task, verifying that
}
long TDotProduct::ExecTime ()
{
	return -1;
}
