/* Generated by Together */

#ifndef TMULTITASK_H
#define TMULTITASK_H
#include "ooptask.h"
//#include "gnudefs.h"
#include "tmultidata.h"
#include "tresultdata.h"
#include "ooptask.h"
//class OOPMReturnType;
class TPZSaveable;

class OOPStorageBuffer;


class TMultiTask : public OOPTask {
public:
	
static	TPZSaveable * Restore(OOPStorageBuffer *buf);
	
//	TMultiTask();
public:
	
	OOPObjectId RhsId;
	
	TMultiTask(int i);
	//TMultiTask(TMultiData & data, TResultData & resdata);
	void SetData(TMultiData & data, TResultData & resdata);
	
    /**
    * Returns the estimated execution time.
    * returns 0 if the task is instantaneous
    * returns > 0 if estimate is known
    * return < 0 if no estimate is known
    */
	virtual long ExecTime ();

    /**
    * Execute the task, verifying that all needed data acesses are satisfied.
    */
	virtual OOPMReturnType Execute ();

    /**
    * Returns last created Id.
    */
	virtual long GetClassID ()
	{
		return 3000;
	}

    /**
    * Virtual Unpack function.
    * Defines the necessary interface for task communication along the network.
    * @param * buf Buffer for data manipulation.
    */
	virtual int Read(OOPStorageBuffer * buf,void *context);

	virtual int Write(OOPStorageBuffer * buf, int classid);

    /**
    * Returns class name
    */
	virtual char *ClassName ()
	{
		return ("TTask");
	}

    /**
    * Returns true if the object belongs to a class derived from the specified classid
    * @param ClassId Id of inquired super class
    */
	int DerivedFrom (long Classid);

    /**
    * Returns true if the object belongs to a class derived from the specified class name
    * @param classname Name of inquired super class
    */
	int DerivedFrom (char *classname);
};
#endif //TMULTITASK_H
