/* Generated by Together */

#ifndef TMULTIDATA_H
#define TMULTIDATA_H
#include "oopmetadata.h"

#include <vector>
#include "pzsave.h"

using namespace std;


class TMultiData : public TPZSaveable {
public:
	TMultiData();
    void SetData(vector<double> & vec);
	long GetClassID();
    vector<double> GetVector();

private:    
    vector<double> fData;
};
#endif //TMULTIDATA_H
