/* Generated by Together */

#include "TLoopFor.h"
/* Generated by Together */
OOPMReturnType TLoopFor::Execute ()
{
#warning "Execute not implemented"
	return ESuccess;	// execute the task, verifying that
}
long TLoopFor::ExecTime ()
{
	return -1;
}
