/* Generated by Together */

#include "LocalCompResidual.h"
OOPMReturnType LocalCompResidual::Execute(){

    return ESuccess; // execute the task, verifying that
}
LocalCompResidual::LocalCompResidual(int ProcId): OOPTast(ProcId) {}
