/* Generated by Together */

#ifndef TCONTRIBUTION_H
#define TCONTRIBUTION_H

/**
 * Implements the necessary information regarded to contribution from one parti-
 * tion ¨i¨ to a partition ¨j¨.
 * Objects of this class populates a matrix which relates partition ¨i¨ to par-
 * tition ¨j¨. Each (i,j) member of this matrix holds a copy of TComtribution.
 * Implements the number of contributing vectors the partition ¨i¨ contains
 * addressed to partition ¨j¨.
 */

class TContribution {
public:

    /**
     * Returns the contribution vector identified by the index parameter
     * @param Index Identifies each vector to be returned
     * @since 23/05/2003 
     */
    vector<TMBData> DestinationVecotor(int index);

private:    

    /**
     * Holds the partition index of the origin partition. 
     */
    int fFrom;

    /**
     * Holds the partition index which will receive the contributions. 
     */
    int fTo;

    /**
     * Holds the indexes of local TMBData which will contribute on neighbor par-
     * tition. Each element on the TMBData has its destination indexes on each
     * TMBData of the fDestination
     */
    vector<int> fLocalIndex;

    /**
     * Indicates the number of contributions between fFrom and fTo partitions. 
     */
    int fNContributions;

    /**
     * Holds TMBData which contains volume indexes from the partition receiving
     * the contribution. 
     */
    vector<TMBData> fDestination;
};
#endif //TCONTRIBUTION_H