/* Generated by Together */

#ifndef TPARCOMPUTE_H
#define TPARCOMPUTE_H
#include "ooptask.h"
class OOPObjectId;
class TParCompute : public OOPTask {
public:    

    TParCompute();

    void SetRhsId(OOPObjectId & Id);

    void SetStateId(OOPObjectId & Id p0);

    void SetMeshId(OOPObjectId & Id p0);
};
#endif //TPARCOMPUTE_H