/* Generated by Together */

#ifndef TPARMESH_H
#define TPARMESH_H
#include "oopsaveable.h"
class TParMesh : public OOPSaveable {
public:    

    TParMesh(int ProcId, int Trace);
};
#endif //TPARMESH_H