/* Generated by Together */

#include "OOPDataLogger.h"
OOPDataLogger::OOPDataLogger(){
    //Initialize ostream pointer
    fLogger=0;
}
OOPDataLogger::OOPDataLogger(ostream & out){
    fLogger=out;
}
OOPDataLogger::OOPDataLogger(string & logfilename){
    fLogger=ofstream(logfilename);
}