/* Generated by Together */

#include "OOPVector.h"

#define OOPVECINT_ID 4040
#define OOPVECDOUBLE_ID 4041
template class TPZRestoreClass<OOPVector < int > , OOPVECINT_ID>;
template class TPZRestoreClass<OOPVector < REAL > , OOPVECDOUBLE_ID>;	
	
OOPVector<REAL>::~OOPVector(){}
OOPVector<int>::~OOPVector(){}
	
int OOPVector<REAL>::ClassId() const {
    return OOPVECDOUBLE_ID;
}
int OOPVector<int>::ClassId() const {
    return OOPVECINT_ID;
}
template <class T>
void OOPVector<T>::Read(TPZStream & buf, void * context){
    TPZSaveable::Read(buf, context);
    int size = 0;
    buf.Read(&size);
    fVecValue.Resize(size);
    buf.Read(&fVecValue[0], size);
    int clsid=0;
    buf.Read(&clsid);
    if(clsid!=ClassId()){
        cerr << "ClassId mismatch on OOPVector::Read";
    }
}
template <class T>
void OOPVector<T>::Write(TPZStream & buf, int withclassid){
    TPZSaveable::Write(buf, withclassid);
    int size = fVecValue.NElements();
    buf.Write(&size);
    buf.Write(&fVecValue[0], size);
    int clsid = ClassId();
    buf.Write(&clsid);
}
