/* Generated by Together */

#ifndef OOPVECTOR_H
#define OOPVECTOR_H
#include "pzsave.h"

template <class T>
class OOPVector : public TPZSaveable {
public:    
	virtual ~OOPVector();
	
    TPZVec<T> fVecValue;
	
    void Write(TPZStream & buf, int withclassid);
	
    void Read(TPZStream & buf, void * context);
	
    virtual int ClassId() const ;
};
#endif //OOPVECTOR_H
