/* Generated by Together */

#ifndef TRESULTDATA_H
#define TRESULTDATA_H
#include "oopmetadata.h"
#include <vector>
#include "oopmetadata.h"

using namespace std;

class TResultData : public OOPMetaData {
public:
	TResultData();
    void SetData(vector<double> & vec);

    vector<double> GetVector();

private:    
    vector<double> fData;
};
#endif //TRESULTDATA_H
