/* Generated by Together */

#include "TDistNorm.h"
/* Generated by Together */


TDistNorm::TDistNorm(int proc) : OOPTask(proc){}
TDistNorm::~TDistNorm(){}

OOPMReturnType TDistNorm::Execute ()
{
#warning "Execute not completely implemented"
	double val = ComputeLocalNorm();
  //On the serial implementation the value of normb is set to 1 if the computed norm is 0
  //How to implement
	TTaskComm * tcmm = new TTaskComm(0);
	tcmm->SetValue(val);
	OOPDataVersion ver;
  OOPMDataDepend dep = fDataDepend.Dep(fId_Target);
  ver = dep.ObjPtr()->Version();
	ver.SetLevelVersion(1,-1);
	tcmm->AddDependentData(OOPMDataDepend(fId_Target, EWriteAccess, ver));
	tcmm->Submit();
	return ESuccess;	// execute the task, verifying that
}
long TDistNorm::ExecTime ()
{
	return -1;
}
double TDistNorm::ComputeLocalNorm(){
#warning "ComputeLocalNorm not implemented"
	return 0.;
}
