/* Generated by Together */

#include "TMultAdd.h"
/* Generated by Together */

TMultAdd::TMultAdd(int proc): OOPTask(proc){}
OOPMReturnType TMultAdd::Execute ()
{
#warning "Execute not implemented"
	return ESuccess;	// execute the task, verifying that
}
long TMultAdd::ExecTime ()
{
	return -1;
}
