/* Generated by Together */

#include "TUpdateResidue.h"
/* Generated by Together */

TUpdateResidue::TUpdateResidue(int nproc) : OOPTask(nproc) {}
OOPMReturnType TUpdateResidue::Execute ()
{
#warning "Execute not implemented"
	return ESuccess;	// execute the task, verifying that
}
long TUpdateResidue::ExecTime ()
{
	return -1;
}
