/* Generated by Together */

#include "TParCompute.h"
TParCompute::TParCompute(){}
void TParCompute::SetMeshId(OOPObjectId & Id p0){}
void TParCompute::SetStateId(OOPObjectId & Id p0){}
void TParCompute::SetRhsId(OOPObjectId & Id){}
