/* Generated by Together */
#include "TParVector.h"

class TPZStream;
TParVector::TParVector ()
{
}
void TParVector::Write (TPZStream & buf, int withclassid)
{
	TPZSaveable::Write(buf,withclassid);
  WriteObjects(buf,fData);
}
void TParVector::Read (TPZStream & buf, void * context)
{
	TPZSaveable::Read(buf,context);
  ReadObjects(buf,fData);
}
void TParVector::SetVector (std::vector < double >data)
{
	fData = data;
}
void TParVector::Resize (int size)
{
	fData.resize (size);
}
TPZSaveable *TParVector::Restore (TPZStream & buf, void * context) {
	TParVector *loc = new TParVector;//();
	loc->Read(buf);
	return loc;
}
