/* Generated by Together */
#ifndef TPARVECTOR_H
#define TPARVECTOR_H
#include "oopsaveable.h"
#include <vector>
class   TParVector:public OOPSaveable
{
      public:
	TParVector ();
	long    GetClassID ();
	int     Pack (OOPStorageBuffer * buf);
	int     Unpack (OOPStorageBuffer * buf);
	void    Resize (int size);
	void    SetVector (vector < double >data);
static OOPSaveable *Restore(OOPStorageBuffer *buf);
      private:
	        vector < double >fData;
};
#endif // TPARRHS_H
