/* Generated by Together */

#include "TLocalCompute.h"
OOPMReturnType TLocalCompute::Execute(){

    return ESuccess; // execute the task, verifying that
}
TLocalCompute::TLocalCompute(int ProcId): OOPTask(ProcId) {}
