/* Generated by Together */

#include "TLocalCompute.h"
void TLocalCompute::InitializePartitionRelationPointer() {
	OOPSaveable *objptr = fDataDepend[0].ObjPtr();
	fPartRelationPtr = dynamic_cast<TPartitionRelation *> (objptr);
}
void TLocalCompute::ComputeLocalFluxes(){}
void TLocalCompute::TransmitFLuxes(TContribution &relation){
    //Criar tarefa de comunicação
    //como fazer isso ?


}
void TLocalCompute::ComputeFrontierFluxes(){}
OOPMReturnType TLocalCompute::Execute(){
        this->InitilizePartitionRelationPointer();

        // message #1.1 to this:TLocalCompute
        this->ComputeFrontierFluxes();

        // message #1.3 to this:TLocalCompute
        this->ComputeLocalFluxes();
        return ESuccess;
    }
TLocalCompute::TLocalCompute(int ProcId): OOPTask(ProcId) {}
