/* Generated by Together */

#include "TPartitionRelation.h"

TPartitionRelation::TPartitionRelation() : OOPSaveable() {}
int TPartitionRelation::OutgoingContribution(int partition){}
int TPartitionRelation::IncomingContribution(int partition){}
int TPartitionRelation::GetNPartitions(){}
long TPartitionRelation::GetClassID(){
	return fClassId;
}
