/* Generated by Together */
#ifndef TPARVECTOR_H
#define TPARVECTOR_H
//#include "oopsaveable.h"
#include <vector>
#include "pzsave.h"
class   TParVector:public TPZSaveable
{
public:
	TParVector ();
	long    GetClassID ();
	int     Write (TPZStream * buf);
	int     Read (TPZStream * buf);
	void    Resize (int size);
	void    SetVector (vector < double >data);
static TPZSaveable * Restore(TPZStream *buf);
private:
	vector < double >fData;
};
#endif // TPARRHS_H
