/* Generated by Together */
#include "TParMesh.h"
class OOPStorageBuffer;
TParMesh::TParMesh ()
{
}
TParMesh::~TParMesh() {
}
  /**
   * Packs the object in on the buffer so it can be transmitted through the network.
   * The Pack function  packs the object's class_id while function Unpack() doesn't,
   * allowing the user to identify the next object to be unpacked.
   * @param *buff A pointer to TSendStorage class to be packed.
   */
int TParMesh::Pack (OOPStorageBuffer * buf) {
	return OOPSaveable::Pack(buf);
}
  /**
   * Unpacks the object class_id
   * @param *buff A pointer to TSendStorage class to be unpacked.
   */
int TParMesh::Unpack (OOPStorageBuffer * buf) {
	return OOPSaveable::Unpack(buf);
}
OOPSaveable *TParMesh::Restore (OOPStorageBuffer * buf) {
	TParMesh *pm = new TParMesh();
	pm->Unpack(buf);
	return pm;
}
