/* Generated by Together */

#ifndef TPARANALYSIS_H
#define TPARANALYSIS_H

#include "TParCompute.h"
#include "TParRhs.h"
#include "TParState.h"
#include "TParMesh.h"
#include "oopdatamanager.h"

/**
 * Implements the functionalities of the Analysis classes incorporating
 * parallelization optimization.
 * This class is not part of the parallel environment, although it make some calls to the Data and Task manager.
 * Its an auxiliar class which triggers the environment.
 */
class TParAnalysis {
public:

    /**
     * Initializes and submit all necessary data and tasks to the Data and Task managers. 
     */
    void ComputeFlux(TPartitionRelation * table);
};
#endif //TPARANALYSIS_H
