/* Generated by Together */

#ifndef TPARSTATE_H
#define TPARSTATE_H
#include "oopsaveable.h"
class TParState : public OOPSaveable {
public:    

    TParState();
	long GetClassID();
	long fClassId;

};
#endif //TPARSTATE_H
