/* Generated by Together */
#include "TParVector.h"

class TPZStream;
TParVector::TParVector ()
{
}

void TParVector::Write (TPZStream & buf, int withclassid)
{
	TPZSaveable::Write(buf,withclassid);
	vector < double >::iterator i = fData.begin ();
	int aux = fData.size ();
	buf.Write (&aux);
	while (i != fData.end ()) {
		buf.Write (&(*i), 1);
	}
}

void TParVector::Read (TPZStream & buf, void * context)
{
	TPZSaveable::Read(buf,context);
	int aux = 0;
	int i = 0;
	buf.Read (&aux);
	double val = 0.;
	for (i = 0; i < aux; i++) {
		buf.Read (&val, 1);
		fData.push_back (val);
	}
}

void TParVector::SetVector (vector < double >data)
{
#ifndef WIN32
#warning "Data should be changed to something else"
#endif
	fData = data;
}

void TParVector::Resize (int size)
{
	fData.resize (size);
}

TPZSaveable *TParVector::Restore (TPZStream & buf, void * context) {
	TParVector *loc = new TParVector;//();
	loc->Read(buf);
	return loc;
}

template class TPZRestoreClass<TParVector, TPARVECTOR_ID>;
