/* Generated by Together */
#ifndef TPARMESH_H
#define TPARMESH_H

#include "fluxdefs.h"
#include "pzsave.h"
class TPZStream;
class   TParMesh:public TPZSaveable
{
      public:
	TParMesh ();
	virtual ~TParMesh();
	/**
	 * Returns the class id for the current class.
	 */
	virtual long GetClassID () {
		return TPARMESH_ID;
	}
  /**
   * Packs the object in on the buffer so it can be transmitted through the network.
   * The Pack function  packs the object's class_id while function Unpack() doesn't,
   * allowing the user to identify the next object to be unpacked.
   * @param *buff A pointer to TSendStorage class to be packed.
   */
	virtual int Write (TPZStream * buf);
  /**
   * Unpacks the object class_id
   * @param *buff A pointer to TSendStorage class to be unpacked.
   */
	virtual int Read (TPZStream * buf);
	static TPZSaveable *Restore (TPZStream * buf);
};
#endif // TPARMESH_H
