/* Generated by Together */

#include "TDotProduct.h"
#include <oopmetadata.h>
#include <TParVector.h>
#include <bicgdouble.h>
/* Generated by Together */
TDotProduct::TDotProduct(int proc) : OOPTask(proc){}
OOPMReturnType TDotProduct::Execute ()
{
#warning "Verify version incrementation for the result"
      TParVector * vec1 = (TParVector*) fDataDepend.Dep(0).ObjPtr()->Ptr();
      TParVector * vec2 = (TParVector*) fDataDepend.Dep(1).ObjPtr()->Ptr();
      BiCGDouble * bresult = (BiCGDouble*) fDataDepend.Dep(2).ObjPtr()->Ptr();
      double * result = &bresult->value;
      int i=0;
      for(i=0;i<vec1->NElements();i++)
            *result += (*vec1)[i]* (*vec2)[i];

      OOPDataVersion bresultver = fDataDepend.Dep(2).ObjPtr()->Version();
      ++bresultver;
      fDataDepend.Dep(2).ObjPtr()->SetVersion(bresultver, Id());
      
	return ESuccess;
}
long TDotProduct::ExecTime ()
{
	return -1;
}
